In [1]:
# ndarry 通用函数
# -*- coding: utf-8 -*-

In [2]:
from __future__ import division
from numpy.random import randn
import numpy as np

In [5]:
# 一维数组
arr = np.arange(10)
# 平方
np.sqrt(arr)
# 指数
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [9]:
# 两个随机数
x = randn(8)
y = randn(8)
print(x, y)
# 对应位置上的最大值
np.maximum(x, y)

[-0.49858123 -0.35965801  0.75259651  1.7435723   0.15511279  0.04265991
  0.52989367  0.14114466] [ 0.24071233 -0.30656777 -0.702074    1.66471752  0.83207264 -1.76336208
 -0.28945325 -0.50624357]


array([ 0.24071233, -0.30656777,  0.75259651,  1.7435723 ,  0.83207264,
        0.04265991,  0.52989367,  0.14114466])

In [10]:
arr = randn(7) * 5
# 返回两个数组，一个浮点数部分，一个整数部分
np.modf(arr)

(array([-0.51778908, -0.45703561,  0.07962361,  0.15084628, -0.1719009 ,
         0.1099868 , -0.20010196]), array([-1., -3.,  5.,  3., -0.,  3., -2.]))

In [13]:
# 向量化
# 利用数组进行数据处理
points = np.arange(-5, 5, 0.01)
# print(points)
xs, ys = np.meshgrid(points, points)
print(ys)

[[-5.   -5.   -5.   ..., -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ..., -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ..., -4.98 -4.98 -4.98]
 ..., 
 [ 4.97  4.97  4.97 ...,  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...,  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...,  4.99  4.99  4.99]]
