In [1]:
import numpy as np

In [16]:
# 点积
# 标准正态分布
arr = np.random.randn(6, 3)
# 转置点积
'''
行 * 列 
A = x * y
B = m * n
A * B = (x * y) * (m * n)
要求 y == m
'''
print(np.dot(arr.T, arr))

# 高维矩阵转换
arr = [0, 1, 2, 3]
# 根据下标重新转换
# reshape -> 参数 2, 3, 0, 1
'''
arr[x][y][z][t] = arr[z][t][y][x]
'''
demo = np.arange(16).reshape((2, 2, 4))
'''
详细解释：
arr数组的内容为
- a[0][0] = [0, 1, 2, 3]
- a[0][1] = [4, 5, 6, 7]
- a[1][0] = [8, 9, 10, 11]
- a[1][1] = [12, 13, 14, 15]
transpose的参数为坐标，正常顺序为(0, 1, 2, ... , n - 1)，
现在传入的为(1, 0, 2)代表a[x][y][z] = a[y][x][z]，第0个和第1个坐标互换。
- a'[0][0] = a[0][0] = [0, 1, 2, 3]
- a'[0][1] = a[1][0] = [8, 9, 10, 11]
- a'[1][0] = a[0][1] = [4, 5, 6, 7]
- a'[1][1] = a[1][1] = [12, 13, 14, 15]
'''
print(demo)
print(demo.transpose((1, 0, 2)))
# swapaxes(1, 2)
# [x][y][z][t] = [x][z][y][t]
print(demo.swapaxes(1, 2))  # 直接交换第1和第2个坐标

# where
a = 2
# a < 3 == True => 6 ! 1
print(np.where(a < 3, 6, 1))

[[ 2.67909725  3.04584471  0.6835294 ]
 [ 3.04584471  6.6438718   0.17508233]
 [ 0.6835294   0.17508233  5.36259733]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]
6
